- platform: template
  switches:
    alarm_chime:
      friendly_name: Chime
      value_template: "{{ is_state_attr('alarm_control_panel.alarm_panel', 'chime', true) }}"
      turn_on:
        service: alarmdecoder.alarm_toggle_chime
        data:
          code: 1006 #currently seems to just activate the alarm system my need to see if changing out 'code' for 'keypress' would work instead 
      turn_off:
        service: alarmdecoder.alarm_toggle_chime
        data:
          code: 1006
      icon_template: >-
          {% if is_state_attr('alarm_control_panel.alarm_panel', 'chime', true) %}
            mdi:bell-ring
          {% else %}
            mdi:bell-off
          {% endif %}
# - platform: circadian_lighting
#   lights_brightness:
#     - light.living_room_lamp_1
#     - light.living_room_lamp_2
#     - light.living_room_lamp_3
#     - light.linear_nortek_security_control_llc_lb60z_1_dimmable_led_light_bulb_level
#     - light.hallway_light
